function cellInfo = ControlBus(varargin) 
% CONTROLBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false;
numEng=1;
numSurf=1;
%if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
if nargin >= 1
    if islogical(varargin{1}) && varargin{1} == false 
      suppressObject = true;
    end
    if nargin == 3
        numEng=varargin{2};
        numSurf=varargin{3};
    end
%elseif nargin > 1 
%    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BUS_CMD', ... 
    'BusCmd.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'EngineCmd', numEng, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EnginePwr', numEng, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CtrlSurfaceCmd', numSurf, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'CtrlSurfacePwr', numSurf, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'GearCmd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
  } ...
  } ...
{ ... 
'BUS_ALLOC', ... 
'BusAlloc.h', ... 
'', ... 
'Exported', ... 
'-1', {... 
{'mdes', 6, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'m0_in', 6, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'B_lon', [6 numEng+numSurf], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'B_lat', [6 numEng+numSurf], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'W_lon', [numEng+numSurf numEng+numSurf], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'W_lat', [numEng+numSurf numEng+numSurf], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'W_lon_inv', [numEng+numSurf numEng+numSurf], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'W_lat_inv', [numEng+numSurf numEng+numSurf], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'u0_in', numEng+numSurf, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'U_Limits_Upp_in', numEng+numSurf, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'U_Limits_Lwr_in', numEng+numSurf, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'u_agi', numEng+numSurf, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'m_obt_flag', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'exc_lim_flag', 1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'u0', numEng+numSurf, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'u0_trim', numEng+numSurf-1, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'x0_trim', 12, 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
  } ...
  } ...
{ ... 
'BUS_CONTROL', ... 
'BusControl.h', ... 
'', ... 
'Exported', ... 
'-1', {... 
{'Cmd', 1, 'Bus: BUS_CMD', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Alloc', 1, 'Bus: BUS_ALLOC', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
} ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo);
end 
