function cellInfo = EnvironmentBus(varargin) 
% ENVIRONMENTBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'EnvironmentBus', ... 
    'BusEnvironment.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Wind', 1, 'Bus: WindBus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Collection of wind data'}; ...
{'Turbulence', 1, 'Bus: TurbulenceBus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Collection of turbulence data.'}; ...
{'Atmosphere', 1, 'Bus: AtmosphereBus', -1, 'real', 'Sample', 'Fixed', [], [], '', 'Collection of atmospheric data'}; ...
    } ...
  } ...
  { ... 
    'WindBus', ... 
    'BusWind.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Vel_wHh', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'ft/s', 'Velocity of the winds in NED frame with NED coordinates.'}; ...
{'VelDtH_wHh', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'ft/s^2', 'Change in velocity of the winds in NED frame with NEW coordinates.'}; ...
    } ...
  } ...
  { ... 
    'TurbulenceBus', ... 
    'BusTurbulence.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Vel_tBb', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'ft/s', 'Velocity of the turbulence in the Body frame with body coordinates.'}; ...
{'VelDtB_tBb', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'ft/s^2', 'Change in velocity of the turbulence in the Body frame with body coordinates.'}; ...
{'Omeg_TBb', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rad/s', 'Angular rate of the turbulent body in body coordinates.'}; ...
{'OmegDtB_TBb', 3, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rad/s^2', 'Change in angular rate of turbulent body in body coordinates.'}; ...
    } ...
  } ...
  { ... 
    'AtmosphereBus', ... 
    'BusAtmosphere.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Density', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'slug/ft^3', 'Current air density at altitude'}; ...
{'Pressure', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'slug/ft^3', 'Current air pressure at altitude'}; ...
{'Temperature', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'rankine', 'Current temperature at altitude'}; ...
{'SpeedOfSound', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], 'ft/s', 'Current speed of sound at altitude based on density, pressure, and temperature.'}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
