function cellInfo = PropActuatorBus(varargin)
% PROPACTUATORBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false;
numEng=1;
if nargin >= 1
    if islogical(varargin{1}) && varargin{1} == false 
      suppressObject = true;
    end
    if nargin == 2
        numEng=varargin{2};
    end
end 

cellInfo = { ... 
  { ... 
    'BUS_PROP_ACTUATOR', ... 
    'BusPropActuator.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'EngSpeed', numEng, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EngAccel', numEng, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Failure', 1, 'Bus: BUS_FAILURE_ENG', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo);
end 
