function cellInfo = SimOutBus(varargin) 
% SIMOUTBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BUS_SIM_OUT', ... 
    'BusSimOut.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Env', 1, 'Bus: EnvironmentBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Vehicle', 1, 'Bus: BUS_VEHICLE_OUT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Control', 1, 'Bus: BUS_CONTROL', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RefInputs', 1, 'Bus: BUS_REF_INPUT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Time', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'InvalidData', 1, 'boolean', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
