function cellInfo = VehicleOutBus(varargin) 
% VEHICLEOUTBUS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'BUS_VEHICLE_OUT', ... 
    'BusVehicleOut.h', ... 
    '', ... 
    'Exported', ... 
    '-1', {... 
{'Power', 1, 'Bus: BUS_POWER_SYSTEM_OUT', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SurfAct', 1, 'Bus: BUS_SURF_ACTUATOR', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'PropAct', 1, 'Bus: BUS_PROP_ACTUATOR', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Gear', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'FM', 1, 'Bus: ForceMomentBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'EOM', 1, 'Bus: EomBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Sensor', 1, 'Bus: SensorBus', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
